# Autostart programms here
exec-once = waybar

# Обои
exec-once=waypaper --restore

# Локскрин и автолок
exec-once = hypridle

# Диалог для разрешения доступа в gui приложениях
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Демон уведомлений
exec-once = swaync

# Фикс чёрного экрана в OBS
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Обои
exec-once = hyprpaper
