# Pavucontrol
windowrulev2 = float, class:(.*org.pulseaudio.pavucontrol.*)
windowrulev2 = center, class:(.*org.pulseaudio.pavucontrol.*)
windowrulev2 = size 700 600, class:(.*org.pulseaudio.pavucontrol.*)
windowrulev2 = pin,class:(.*org.pulseaudio.pavucontrol.*)

# Firefox popups
windowrulev2 = float, class:(firefox), title:(Library)
windowrulev2 = size 1000 800, class:(firefox), title:(Library)

# Rofi
windowrule = stayfocused, class:(Rofi)

# Alacritty
windowrule = float, class:(Alacritty)
windowrule = size 1100 700, class:(Alacritty)

# PyQt5 developing apps
windowrulev2 = float, class:(python3)
windowrulev2 = size 800 600, class:(python3)

# Cava(to disable dimming)
windowrule = nodim, title:(cava)

# Calendar
windowrule = float, class:(org.gnome.Calendar)
windowrule = center, class:(org.gnome.Calendar)
windowrule = size 1100 800, class:(org.gnome.Calendar)

# Waypaper
windowrule = float, class:(waypaper), title:(Waypaper)
windowrule = center, class:(waypaper), title:(Waypaper)
windowrule = size 1000 800, class:(waypaper), title:(Waypaper)

# Zoom
windowrule = stayfocused, title:(menu window), class:(zoom)
windowrule = stayfocused, title:(meeting bottombar popup), class:(zoom)

# System monitor
windowrule = float, class:(org.gnome.SystemMonitor)
windowrule = center, class:(org.gnome.SystemMonitor)
windowrule = size 1100 800, class:(org.gnome.SystemMonitor)
